CREATE TABLE IF NOT EXISTS `dishes` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `dname` VARCHAR(255) DEFAULT NULL,
  `dtype` VARCHAR(255) DEFAULT NULL,
  `dprice` DECIMAL(10,2) DEFAULT 0.00,
  `dtime` VARCHAR(50) DEFAULT NULL,
  `photo` VARCHAR(255) DEFAULT NULL,
  `discription` TEXT,
  `ddiscount` DECIMAL(5,2) DEFAULT 0.00,
  `dserve` INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
